### ISSUE TITLE
Endpoint to start exec

### ISSUE THREAD

**Issue by alvdef** [UNIZAR-30226-2024-03/Backend#12]
Enpoint al que se le hara una request al cargar la pagina y que pondra el estado anterior en el reproductor.
Devolvera la cancion y segundo de la misma en el que se dejo de reproducir para poder retomarla.
Valorar si guardar la playlist que estaba reproduciendo para seguir con esta.

**Comment by daniihc16** [comment]
Esto no debería devolverlo el login?
